sonar.projectKey=Roskus_prospero-flow-crm
sonar.organization=roskus
sonar.projectVersion=${APP_VERSION}

# PHP configuration
sonar.sources=app,config,routes,bootstrap
sonar.tests=tests
sonar.php.coverage.reportPaths=coverage.xml

# Exclusions
sonar.exclusions=**/CreatesApplication.php,vendor/**,node_modules/**,storage/**,bootstrap/cache/**
sonar.test.exclusions=tests/CreatesApplication.php

# Code duplication
sonar.cpd.exclusions=tests/**
